import IECore

import Gaffer

import AtomsGaffer

import DocumentationAlgo

Gaffer.Metadata.registerNode(

    AtomsGaffer.AtomsCrowdGenerator,

    "description",
    """
    Generates a fully deformed crowd of agents by combining the input crowd points
    from the primary scene, and the specified agents from the right-hand scene.
    """,

    "icon", "atoms_logo.png",
    "documentation:url", DocumentationAlgo.documentationURL,

    plugs = {

        "parent" : [

            "description",
            """
			The location of the crowd points in the input scene. The
			per-vertex primitive variable "\agentType\" will be used
			to determine which agents to instantiate. It must contain
			indexed string data (ie. as generated by AtomsCrowdReader).
			"""

        ],

        "name" : [

            "description",
            """
            The name of the new location containing the generated agents.
            """,

        ],

        "agents" : [

            "description",
            """
			The scene containing the agents to be applied to each vertex of
			the crowd. Specify multiple agents by parenting them at the root
			of the scene :

			- /agent0
			- /agent1
			- /agent2

			Be sure to order the agents to match the \"agentType\" data provided
			on the input crowd points.

			Note that the agents are not limited to being a
			single object : they can each have arbitrary child
			hierarchies.
			""",

            "plugValueWidget:type", "",

        ],

        "attributes" : [

            "description",
            """
			The names of per-vertex primitive variables to be turned into
			per-agent attributes. Names should be separated by spaces and
			can use Gaffer's standard wildcards.
			""",

        ],

        "mode" : [

            "description",
            """
            Compute mode
             0 - Hierarchy of the full crowd, including per-agent locations (with geometry)
             1 - Hierarchy of the full crowd, including per-agent locations (no geometry)
             2 - Hierarchy of the full crowd, terminating at the start of each agent (with capsules)
                A Capsule is akin to an on-the-fly procedural, or Houdini packed-prim
             3 - Hierarchy of the full crowd, terminating at the start of each agent (no geometry)
             4 - Hierarchy of the full crowd, terminating at the start of each agent (one point per agent)
                A single location point cloud of the entire crowd (each point represents one agent)
                Per-Agent skeleton representation of the crowd (one location per agent, one point &
            """
        ],

    },

)
